// Полный список всех 114 сур Корана
// Перевод: Эльмир Кулиев

export interface SurahInfo {
  id: number;
  nameArabic: string;
  nameRussian: string;
  nameEnglish: string;
  versesCount: number;
  revelationType: 'Meccan' | 'Medinan';
}

export const allSurahs: SurahInfo[] = [
  { id: 1, nameArabic: "الفاتحة", nameRussian: "Аль-Фатиха (Открывающая)", nameEnglish: "Al-Fatiha", versesCount: 7, revelationType: "Meccan" },
  { id: 2, nameArabic: "البقرة", nameRussian: "Аль-Бакара (Корова)", nameEnglish: "Al-Baqarah", versesCount: 286, revelationType: "Medinan" },
  { id: 3, nameArabic: "آل عمران", nameRussian: "Аль-Имран (Семейство Имрана)", nameEnglish: "Ali 'Imran", versesCount: 200, revelationType: "Medinan" },
  { id: 4, nameArabic: "النساء", nameRussian: "Ан-Ниса (Женщины)", nameEnglish: "An-Nisa", versesCount: 176, revelationType: "Medinan" },
  { id: 5, nameArabic: "المائدة", nameRussian: "Аль-Маида (Трапеза)", nameEnglish: "Al-Ma'idah", versesCount: 120, revelationType: "Medinan" },
  { id: 6, nameArabic: "الأنعام", nameRussian: "Аль-Анам (Скот)", nameEnglish: "Al-An'am", versesCount: 165, revelationType: "Meccan" },
  { id: 7, nameArabic: "الأعراف", nameRussian: "Аль-Араф (Преграды)", nameEnglish: "Al-A'raf", versesCount: 206, revelationType: "Meccan" },
  { id: 8, nameArabic: "الأنفال", nameRussian: "Аль-Анфаль (Добыча)", nameEnglish: "Al-Anfal", versesCount: 75, revelationType: "Medinan" },
  { id: 9, nameArabic: "التوبة", nameRussian: "Ат-Тауба (Покаяние)", nameEnglish: "At-Tawbah", versesCount: 129, revelationType: "Medinan" },
  { id: 10, nameArabic: "يونس", nameRussian: "Юнус (Иона)", nameEnglish: "Yunus", versesCount: 109, revelationType: "Meccan" },
  { id: 11, nameArabic: "هود", nameRussian: "Худ", nameEnglish: "Hud", versesCount: 123, revelationType: "Meccan" },
  { id: 12, nameArabic: "يوسف", nameRussian: "Юсуф (Иосиф)", nameEnglish: "Yusuf", versesCount: 111, revelationType: "Meccan" },
  { id: 13, nameArabic: "الرعد", nameRussian: "Ар-Раад (Гром)", nameEnglish: "Ar-Ra'd", versesCount: 43, revelationType: "Medinan" },
  { id: 14, nameArabic: "إبراهيم", nameRussian: "Ибрахим (Авраам)", nameEnglish: "Ibrahim", versesCount: 52, revelationType: "Meccan" },
  { id: 15, nameArabic: "الحجر", nameRussian: "Аль-Хиджр (Хиджр)", nameEnglish: "Al-Hijr", versesCount: 99, revelationType: "Meccan" },
  { id: 16, nameArabic: "النحل", nameRussian: "Ан-Нахль (Пчёлы)", nameEnglish: "An-Nahl", versesCount: 128, revelationType: "Meccan" },
  { id: 17, nameArabic: "الإسراء", nameRussian: "Аль-Исра (Ночной перенос)", nameEnglish: "Al-Isra", versesCount: 111, revelationType: "Meccan" },
  { id: 18, nameArabic: "الكهف", nameRussian: "Аль-Кахф (Пещера)", nameEnglish: "Al-Kahf", versesCount: 110, revelationType: "Meccan" },
  { id: 19, nameArabic: "مريم", nameRussian: "Марьям (Мария)", nameEnglish: "Maryam", versesCount: 98, revelationType: "Meccan" },
  { id: 20, nameArabic: "طه", nameRussian: "Та Ха", nameEnglish: "Taha", versesCount: 135, revelationType: "Meccan" },
  { id: 21, nameArabic: "الأنبياء", nameRussian: "Аль-Анбийа (Пророки)", nameEnglish: "Al-Anbiya", versesCount: 112, revelationType: "Meccan" },
  { id: 22, nameArabic: "الحج", nameRussian: "Аль-Хадж (Паломничество)", nameEnglish: "Al-Hajj", versesCount: 78, revelationType: "Medinan" },
  { id: 23, nameArabic: "المؤمنون", nameRussian: "Аль-Муминун (Верующие)", nameEnglish: "Al-Mu'minun", versesCount: 118, revelationType: "Meccan" },
  { id: 24, nameArabic: "النور", nameRussian: "Ан-Нур (Свет)", nameEnglish: "An-Nur", versesCount: 64, revelationType: "Medinan" },
  { id: 25, nameArabic: "الفرقان", nameRussian: "Аль-Фуркан (Различение)", nameEnglish: "Al-Furqan", versesCount: 77, revelationType: "Meccan" },
  { id: 26, nameArabic: "الشعراء", nameRussian: "Аш-Шуара (Поэты)", nameEnglish: "Ash-Shu'ara", versesCount: 227, revelationType: "Meccan" },
  { id: 27, nameArabic: "النمل", nameRussian: "Ан-Намль (Муравьи)", nameEnglish: "An-Naml", versesCount: 93, revelationType: "Meccan" },
  { id: 28, nameArabic: "القصص", nameRussian: "Аль-Касас (Рассказ)", nameEnglish: "Al-Qasas", versesCount: 88, revelationType: "Meccan" },
  { id: 29, nameArabic: "العنكبوت", nameRussian: "Аль-Анкабут (Паук)", nameEnglish: "Al-'Ankabut", versesCount: 69, revelationType: "Meccan" },
  { id: 30, nameArabic: "الروم", nameRussian: "Ар-Рум (Римляне)", nameEnglish: "Ar-Rum", versesCount: 60, revelationType: "Meccan" },
  { id: 31, nameArabic: "لقمان", nameRussian: "Лукман", nameEnglish: "Luqman", versesCount: 34, revelationType: "Meccan" },
  { id: 32, nameArabic: "السجدة", nameRussian: "Ас-Саджда (Поклон)", nameEnglish: "As-Sajdah", versesCount: 30, revelationType: "Meccan" },
  { id: 33, nameArabic: "الأحزاب", nameRussian: "Аль-Ахзаб (Союзники)", nameEnglish: "Al-Ahzab", versesCount: 73, revelationType: "Medinan" },
  { id: 34, nameArabic: "سبأ", nameRussian: "Саба (Сава)", nameEnglish: "Saba", versesCount: 54, revelationType: "Meccan" },
  { id: 35, nameArabic: "فاطر", nameRussian: "Фатыр (Творец)", nameEnglish: "Fatir", versesCount: 45, revelationType: "Meccan" },
  { id: 36, nameArabic: "يس", nameRussian: "Йа Син", nameEnglish: "Ya-Sin", versesCount: 83, revelationType: "Meccan" },
  { id: 37, nameArabic: "الصافات", nameRussian: "Ас-Саффат (Выстроившиеся в ряды)", nameEnglish: "As-Saffat", versesCount: 182, revelationType: "Meccan" },
  { id: 38, nameArabic: "ص", nameRussian: "Сад", nameEnglish: "Sad", versesCount: 88, revelationType: "Meccan" },
  { id: 39, nameArabic: "الزمر", nameRussian: "Аз-Зумар (Толпы)", nameEnglish: "Az-Zumar", versesCount: 75, revelationType: "Meccan" },
  { id: 40, nameArabic: "غافر", nameRussian: "Гафир (Прощающий)", nameEnglish: "Ghafir", versesCount: 85, revelationType: "Meccan" },
  { id: 41, nameArabic: "فصلت", nameRussian: "Фуссылят (Разъяснены)", nameEnglish: "Fussilat", versesCount: 54, revelationType: "Meccan" },
  { id: 42, nameArabic: "الشورى", nameRussian: "Аш-Шура (Совет)", nameEnglish: "Ash-Shura", versesCount: 53, revelationType: "Meccan" },
  { id: 43, nameArabic: "الزخرف", nameRussian: "Аз-Зухруф (Украшения)", nameEnglish: "Az-Zukhruf", versesCount: 89, revelationType: "Meccan" },
  { id: 44, nameArabic: "الدخان", nameRussian: "Ад-Духан (Дым)", nameEnglish: "Ad-Dukhan", versesCount: 59, revelationType: "Meccan" },
  { id: 45, nameArabic: "الجاثية", nameRussian: "Аль-Джасийа (Коленопреклонённые)", nameEnglish: "Al-Jathiyah", versesCount: 37, revelationType: "Meccan" },
  { id: 46, nameArabic: "الأحقاف", nameRussian: "Аль-Ахкаф (Барханы)", nameEnglish: "Al-Ahqaf", versesCount: 35, revelationType: "Meccan" },
  { id: 47, nameArabic: "محمد", nameRussian: "Мухаммад", nameEnglish: "Muhammad", versesCount: 38, revelationType: "Medinan" },
  { id: 48, nameArabic: "الفتح", nameRussian: "Аль-Фатх (Победа)", nameEnglish: "Al-Fath", versesCount: 29, revelationType: "Medinan" },
  { id: 49, nameArabic: "الحجرات", nameRussian: "Аль-Худжурат (Комнаты)", nameEnglish: "Al-Hujurat", versesCount: 18, revelationType: "Medinan" },
  { id: 50, nameArabic: "ق", nameRussian: "Каф", nameEnglish: "Qaf", versesCount: 45, revelationType: "Meccan" },
  { id: 51, nameArabic: "الذاريات", nameRussian: "Аз-Зарийат (Рассеивающие)", nameEnglish: "Adh-Dhariyat", versesCount: 60, revelationType: "Meccan" },
  { id: 52, nameArabic: "الطور", nameRussian: "Ат-Тур (Гора)", nameEnglish: "At-Tur", versesCount: 49, revelationType: "Meccan" },
  { id: 53, nameArabic: "النجم", nameRussian: "Ан-Наджм (Звезда)", nameEnglish: "An-Najm", versesCount: 62, revelationType: "Meccan" },
  { id: 54, nameArabic: "القمر", nameRussian: "Аль-Камар (Луна)", nameEnglish: "Al-Qamar", versesCount: 55, revelationType: "Meccan" },
  { id: 55, nameArabic: "الرحمن", nameRussian: "Ар-Рахман (Милостивый)", nameEnglish: "Ar-Rahman", versesCount: 78, revelationType: "Medinan" },
  { id: 56, nameArabic: "الواقعة", nameRussian: "Аль-Вакиа (Событие)", nameEnglish: "Al-Waqi'ah", versesCount: 96, revelationType: "Meccan" },
  { id: 57, nameArabic: "الحديد", nameRussian: "Аль-Хадид (Железо)", nameEnglish: "Al-Hadid", versesCount: 29, revelationType: "Medinan" },
  { id: 58, nameArabic: "المجادلة", nameRussian: "Аль-Муджадиля (Препирающаяся)", nameEnglish: "Al-Mujadila", versesCount: 22, revelationType: "Medinan" },
  { id: 59, nameArabic: "الحشر", nameRussian: "Аль-Хашр (Сбор)", nameEnglish: "Al-Hashr", versesCount: 24, revelationType: "Medinan" },
  { id: 60, nameArabic: "الممتحنة", nameRussian: "Аль-Мумтахана (Испытуемая)", nameEnglish: "Al-Mumtahanah", versesCount: 13, revelationType: "Medinan" },
  { id: 61, nameArabic: "الصف", nameRussian: "Ас-Сафф (Ряд)", nameEnglish: "As-Saff", versesCount: 14, revelationType: "Medinan" },
  { id: 62, nameArabic: "الجمعة", nameRussian: "Аль-Джумуа (Пятница)", nameEnglish: "Al-Jumu'ah", versesCount: 11, revelationType: "Medinan" },
  { id: 63, nameArabic: "المنافقون", nameRussian: "Аль-Мунафикун (Лицемеры)", nameEnglish: "Al-Munafiqun", versesCount: 11, revelationType: "Medinan" },
  { id: 64, nameArabic: "التغابن", nameRussian: "Ат-Тагабун (Взаимное обделение)", nameEnglish: "At-Taghabun", versesCount: 18, revelationType: "Medinan" },
  { id: 65, nameArabic: "الطلاق", nameRussian: "Ат-Талак (Развод)", nameEnglish: "At-Talaq", versesCount: 12, revelationType: "Medinan" },
  { id: 66, nameArabic: "التحريم", nameRussian: "Ат-Тахрим (Запрещение)", nameEnglish: "At-Tahrim", versesCount: 12, revelationType: "Medinan" },
  { id: 67, nameArabic: "الملك", nameRussian: "Аль-Мульк (Власть)", nameEnglish: "Al-Mulk", versesCount: 30, revelationType: "Meccan" },
  { id: 68, nameArabic: "القلم", nameRussian: "Аль-Калям (Перо)", nameEnglish: "Al-Qalam", versesCount: 52, revelationType: "Meccan" },
  { id: 69, nameArabic: "الحاقة", nameRussian: "Аль-Хакка (Неизбежное)", nameEnglish: "Al-Haqqah", versesCount: 52, revelationType: "Meccan" },
  { id: 70, nameArabic: "المعارج", nameRussian: "Аль-Мааридж (Ступени)", nameEnglish: "Al-Ma'arij", versesCount: 44, revelationType: "Meccan" },
  { id: 71, nameArabic: "نوح", nameRussian: "Нух (Ной)", nameEnglish: "Nuh", versesCount: 28, revelationType: "Meccan" },
  { id: 72, nameArabic: "الجن", nameRussian: "Аль-Джинн (Джинны)", nameEnglish: "Al-Jinn", versesCount: 28, revelationType: "Meccan" },
  { id: 73, nameArabic: "المزمل", nameRussian: "Аль-Муззаммиль (Закутавшийся)", nameEnglish: "Al-Muzzammil", versesCount: 20, revelationType: "Meccan" },
  { id: 74, nameArabic: "المدثر", nameRussian: "Аль-Муддассир (Завернувшийся)", nameEnglish: "Al-Muddaththir", versesCount: 56, revelationType: "Meccan" },
  { id: 75, nameArabic: "القيامة", nameRussian: "Аль-Кийама (Воскресение)", nameEnglish: "Al-Qiyamah", versesCount: 40, revelationType: "Meccan" },
  { id: 76, nameArabic: "الإنسان", nameRussian: "Аль-Инсан (Человек)", nameEnglish: "Al-Insan", versesCount: 31, revelationType: "Medinan" },
  { id: 77, nameArabic: "المرسلات", nameRussian: "Аль-Мурсалят (Посылаемые)", nameEnglish: "Al-Mursalat", versesCount: 50, revelationType: "Meccan" },
  { id: 78, nameArabic: "النبأ", nameRussian: "Ан-Наба (Весть)", nameEnglish: "An-Naba", versesCount: 40, revelationType: "Meccan" },
  { id: 79, nameArabic: "النازعات", nameRussian: "Ан-Назиат (Вырывающие)", nameEnglish: "An-Nazi'at", versesCount: 46, revelationType: "Meccan" },
  { id: 80, nameArabic: "عبس", nameRussian: "Абаса (Нахмурился)", nameEnglish: "'Abasa", versesCount: 42, revelationType: "Meccan" },
  { id: 81, nameArabic: "التكوير", nameRussian: "Ат-Таквир (Скручивание)", nameEnglish: "At-Takwir", versesCount: 29, revelationType: "Meccan" },
  { id: 82, nameArabic: "الانفطار", nameRussian: "Аль-Инфитар (Раскалывание)", nameEnglish: "Al-Infitar", versesCount: 19, revelationType: "Meccan" },
  { id: 83, nameArabic: "المطففين", nameRussian: "Аль-Мутаффифин (Обвешивающие)", nameEnglish: "Al-Mutaffifin", versesCount: 36, revelationType: "Meccan" },
  { id: 84, nameArabic: "الانشقاق", nameRussian: "Аль-Иншикак (Разверзнется)", nameEnglish: "Al-Inshiqaq", versesCount: 25, revelationType: "Meccan" },
  { id: 85, nameArabic: "البروج", nameRussian: "Аль-Бурудж (Созвездия)", nameEnglish: "Al-Buruj", versesCount: 22, revelationType: "Meccan" },
  { id: 86, nameArabic: "الطارق", nameRussian: "Ат-Тарик (Ночной путник)", nameEnglish: "At-Tariq", versesCount: 17, revelationType: "Meccan" },
  { id: 87, nameArabic: "الأعلى", nameRussian: "Аль-Аля (Высочайший)", nameEnglish: "Al-A'la", versesCount: 19, revelationType: "Meccan" },
  { id: 88, nameArabic: "الغاشية", nameRussian: "Аль-Гашийа (Покрывающее)", nameEnglish: "Al-Ghashiyah", versesCount: 26, revelationType: "Meccan" },
  { id: 89, nameArabic: "الفجر", nameRussian: "Аль-Фаджр (Заря)", nameEnglish: "Al-Fajr", versesCount: 30, revelationType: "Meccan" },
  { id: 90, nameArabic: "البلد", nameRussian: "Аль-Баляд (Город)", nameEnglish: "Al-Balad", versesCount: 20, revelationType: "Meccan" },
  { id: 91, nameArabic: "الشمس", nameRussian: "Аш-Шамс (Солнце)", nameEnglish: "Ash-Shams", versesCount: 15, revelationType: "Meccan" },
  { id: 92, nameArabic: "الليل", nameRussian: "Аль-Лейль (Ночь)", nameEnglish: "Al-Layl", versesCount: 21, revelationType: "Meccan" },
  { id: 93, nameArabic: "الضحى", nameRussian: "Ад-Духа (Утро)", nameEnglish: "Ad-Duhaa", versesCount: 11, revelationType: "Meccan" },
  { id: 94, nameArabic: "الشرح", nameRussian: "Аш-Шарх (Раскрытие)", nameEnglish: "Ash-Sharh", versesCount: 8, revelationType: "Meccan" },
  { id: 95, nameArabic: "التين", nameRussian: "Ат-Тин (Смоковница)", nameEnglish: "At-Tin", versesCount: 8, revelationType: "Meccan" },
  { id: 96, nameArabic: "العلق", nameRussian: "Аль-Аляк (Сгусток)", nameEnglish: "Al-'Alaq", versesCount: 19, revelationType: "Meccan" },
  { id: 97, nameArabic: "القدر", nameRussian: "Аль-Кадр (Могущество)", nameEnglish: "Al-Qadr", versesCount: 5, revelationType: "Meccan" },
  { id: 98, nameArabic: "البينة", nameRussian: "Аль-Баййина (Ясное знамение)", nameEnglish: "Al-Bayyinah", versesCount: 8, revelationType: "Medinan" },
  { id: 99, nameArabic: "الزلزلة", nameRussian: "Аз-Зальзаля (Землетрясение)", nameEnglish: "Az-Zalzalah", versesCount: 8, revelationType: "Medinan" },
  { id: 100, nameArabic: "العاديات", nameRussian: "Аль-Адийят (Скачущие)", nameEnglish: "Al-'Adiyat", versesCount: 11, revelationType: "Meccan" },
  { id: 101, nameArabic: "القارعة", nameRussian: "Аль-Кариа (Великое бедствие)", nameEnglish: "Al-Qari'ah", versesCount: 11, revelationType: "Meccan" },
  { id: 102, nameArabic: "التكاثر", nameRussian: "Ат-Такасур (Приумножение)", nameEnglish: "At-Takathur", versesCount: 8, revelationType: "Meccan" },
  { id: 103, nameArabic: "العصر", nameRussian: "Аль-Аср (Время)", nameEnglish: "Al-'Asr", versesCount: 3, revelationType: "Meccan" },
  { id: 104, nameArabic: "الهمزة", nameRussian: "Аль-Хумаза (Хулитель)", nameEnglish: "Al-Humazah", versesCount: 9, revelationType: "Meccan" },
  { id: 105, nameArabic: "الفيل", nameRussian: "Аль-Филь (Слон)", nameEnglish: "Al-Fil", versesCount: 5, revelationType: "Meccan" },
  { id: 106, nameArabic: "قريش", nameRussian: "Курайш", nameEnglish: "Quraysh", versesCount: 4, revelationType: "Meccan" },
  { id: 107, nameArabic: "الماعون", nameRussian: "Аль-Маун (Мелочь)", nameEnglish: "Al-Ma'un", versesCount: 7, revelationType: "Meccan" },
  { id: 108, nameArabic: "الكوثر", nameRussian: "Аль-Каусар (Изобилие)", nameEnglish: "Al-Kawthar", versesCount: 3, revelationType: "Meccan" },
  { id: 109, nameArabic: "الكافرون", nameRussian: "Аль-Кафирун (Неверующие)", nameEnglish: "Al-Kafirun", versesCount: 6, revelationType: "Meccan" },
  { id: 110, nameArabic: "النصر", nameRussian: "Ан-Наср (Помощь)", nameEnglish: "An-Nasr", versesCount: 3, revelationType: "Medinan" },
  { id: 111, nameArabic: "المسد", nameRussian: "Аль-Масад (Пальмовые волокна)", nameEnglish: "Al-Masad", versesCount: 5, revelationType: "Meccan" },
  { id: 112, nameArabic: "الإخلاص", nameRussian: "Аль-Ихлас (Искренность)", nameEnglish: "Al-Ikhlas", versesCount: 4, revelationType: "Meccan" },
  { id: 113, nameArabic: "الفلق", nameRussian: "Аль-Фаляк (Рассвет)", nameEnglish: "Al-Falaq", versesCount: 5, revelationType: "Meccan" },
  { id: 114, nameArabic: "الناس", nameRussian: "Ан-Нас (Люди)", nameEnglish: "An-Nas", versesCount: 6, revelationType: "Meccan" },
];

// Общее количество аятов в Коране
export const totalVerses = allSurahs.reduce((sum, surah) => sum + surah.versesCount, 0); // 6236
